POST http://localhost:5000/reports
content-type: application/json

{
  "make": "Toyota",
  "model": "Corolla",
  "year": 1980,
  "mileage": 100000,
  "lng": 0,
  "lat": 0,
  "price": 500000
}

### Approve an exisitinng report

PATCH http://localhost:5000/reports/approve/1
content-type: application/json

{
  "approved": true
}


### Get specific report
GET http://localhost:5000/reports/1