POST http://localhost:5000/reports
content-type: application/json

{
  "make": "Ford",
  "model": "Mustang",
  "year": 1982,
  "mileage": 5000,
  "lng": 45,
  "lat": 45,
  "price": 20000
}

### Approve an exisitinng report

PATCH http://localhost:5000/reports/approve/1
content-type: application/json

{
  "approved": true
}


### Get specific report
GET http://localhost:5000/reports/1

### Get report estimate

GET http://localhost:5000/reports/estimate?make=Ford&model=Mustang&year=1982&mileage=2000&lng=0&lat=0
