POST http://localhost:3000/auth/signup 
content-Type: application/json

{
  "email":"test@email.com",
  "password": "test@123"
}

### Find user with specific id

GET http://localhost:3000/auth/1


### Find users by email

GET http://localhost:3000/auth?email=test2@gmail.com

### Delete user with a given is

DELETE http://localhost:3000/auth/1

### Update a user email

PATCH http://localhost:3000/auth/2
content-Type: application/json

{
  "email" : "test2@gmail.com"
}

### Update a user password

PATCH http://localhost:3000/auth/2
content-Type: application/json

{
  "password" : "test@124"
}

