POST http://localhost:5000/auth/signup 
content-Type: application/json

{
  "email":"test@email.com",
  "password": "12345"
}

### Find user with specific id

GET http://localhost:5000/auth/1


### Find users by email

GET http://localhost:5000/auth?email=test2@gmail.com

### Delete user with a given is

DELETE http://localhost:5000/auth/4

### Update a user email

PATCH http://localhost:5000/auth/2
content-Type: application/json

{
  "email" : "test2@gmail.com"
}

### Update a user password

PATCH http://localhost:5000/auth/2
content-Type: application/json

{
  "password" : "test@124"
}

### Signin
POST http://localhost:5000/auth/sign-in 
content-Type: application/json

{
  "email":"test@email.com",
  "password": "12345"
}

### Signout

POST http://localhost:5000/auth/sign-out

### Get curret user

POST http://localhost:5000/auth/current-user


### Get current user
GET http://localhost:5000/auth/who-am-i


